ARG ELIXIR_VERSION=1.5.2
FROM livinginthepast/elixir-hex-phantomjs:$ELIXIR_VERSION

RUN \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -q \
    && apt-get install -y \
      yarn \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

