ARG ELIXIR_VERSION=1.9.0
ARG OTP_VERSION=22.0.4
FROM livinginthepast/elixir-hex:$OTP_VERSION-$ELIXIR_VERSION

RUN \
  wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -q \
    && apt-get install -y \
      yarn \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

