ARG TAG
FROM livinginthepast/elixir-hex:${TAG}

RUN \
  wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -q \
    && apt-get install -y \
      yarn \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

